[local]
localhost ansible_connection=local

[containers]
demo-app ansible_connection=docker ansible_host=demo-app
prometheus ansible_connection=docker ansible_host=prometheus
grafana ansible_connection=docker ansible_host=grafana
